apiVersion: v1
kind: Service
metadata:
  name: cc-management-app-service
  namespace: credit-card-app
spec:
  type: NodePort
  selector:
    app: cc-management-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010

