jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.organization=CreditCardWebApp \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
