jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.organization=<your_organization> \
            -Dsonar.host.url=<your_sonarqube_url> \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
